title: <p align="center"> Tunisha Varshney</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="linkedin.com/in/tunisha-varshney-16490a4a/">LinkedIn</a> |
  <a href="https://github.com/tunisha">GitHub</a>
  
  <br>   
  I am currently pursuing Executive PG Programme in Machine Learning & AI from IIIT-B and Ph.D. from NIT Delhi.I have worked on various engineering institute as a Assistant Professor. I have four year of experience in that. I have also worked as Data Science intern in Evolv Fit. 
  <br>
  </p>



theme: jekyll-theme-minimal
