title: <p align="center"> Tunisha Varshney</p>
logo: /assets/img/profile.png

description:
  <p align="center">
  |
  <a href="https://www.linkedin.com/in/tunisha-varshney-16490a4a/">LinkedIn</a> |
  <a href="https://github.com/tunisha">GitHub</a>
  
  <br>   
  
  <br>
  </p>










theme: jekyll-theme-minimal
